import { PrismaClient } from '@prisma/client';

const kana = [
  {
    romaji: 'a',
    type: 'gojuuon',
    ru: 'а',
    hiragana: 'あ',
    katakana: 'ア',
  },
  {
    romaji: 'i',
    type: 'gojuuon',
    ru: 'и',
    hiragana: 'い',
    katakana: 'イ',
  },
  {
    romaji: 'u',
    type: 'gojuuon',
    ru: 'у',
    hiragana: 'う',
    katakana: 'ウ',
  },
  {
    romaji: 'e',
    type: 'gojuuon',
    ru: 'э',
    hiragana: 'え',
    katakana: 'エ',
  },
  {
    romaji: 'o',
    type: 'gojuuon',
    ru: 'о',
    hiragana: 'お',
    katakana: 'オ',
  },
  {
    romaji: 'ka',
    type: 'gojuuon',
    ru: 'ка',
    hiragana: 'か',
    katakana: 'カ',
  },
  {
    romaji: 'ki',
    type: 'gojuuon',
    ru: 'ки',
    hiragana: 'き',
    katakana: 'キ',
  },
  {
    romaji: 'ku',
    type: 'gojuuon',
    ru: 'ку',
    hiragana: 'く',
    katakana: 'ク',
  },
  {
    romaji: 'ke',
    type: 'gojuuon',
    ru: 'кэ',
    hiragana: 'け',
    katakana: 'ケ',
  },
  {
    romaji: 'ko',
    type: 'gojuuon',
    ru: 'ко',
    hiragana: 'こ',
    katakana: 'コ',
  },
  {
    romaji: 'sa',
    type: 'gojuuon',
    ru: 'са',
    hiragana: 'さ',
    katakana: 'サ',
  },
  {
    romaji: 'shi',
    type: 'gojuuon',
    ru: 'си',
    hiragana: 'し',
    katakana: 'シ',
  },
  {
    romaji: 'su',
    type: 'gojuuon',
    ru: 'су',
    hiragana: 'す',
    katakana: 'ス',
  },
  {
    romaji: 'se',
    type: 'gojuuon',
    ru: 'сэ',
    hiragana: 'せ',
    katakana: 'セ',
  },
  {
    romaji: 'so',
    type: 'gojuuon',
    ru: 'со',
    hiragana: 'そ',
    katakana: 'ソ',
  },
  {
    romaji: 'ta',
    type: 'gojuuon',
    ru: 'та',
    hiragana: 'た',
    katakana: 'タ',
  },
  {
    romaji: 'chi',
    type: 'gojuuon',
    ru: 'ти',
    hiragana: 'ち',
    katakana: 'チ',
  },
  {
    romaji: 'tsu',
    type: 'gojuuon',
    ru: 'цу',
    hiragana: 'つ',
    katakana: 'ツ',
  },
  {
    romaji: 'te',
    type: 'gojuuon',
    ru: 'тэ',
    hiragana: 'て',
    katakana: 'テ',
  },
  {
    romaji: 'to',
    type: 'gojuuon',
    ru: 'то',
    hiragana: 'と',
    katakana: 'ト',
  },
  {
    romaji: 'na',
    type: 'gojuuon',
    ru: 'на',
    hiragana: 'な',
    katakana: 'ナ',
  },
  {
    romaji: 'ni',
    type: 'gojuuon',
    ru: 'ни',
    hiragana: 'に',
    katakana: 'ニ',
  },
  {
    romaji: 'nu',
    type: 'gojuuon',
    ru: 'ну',
    hiragana: 'ぬ',
    katakana: 'ヌ',
  },
  {
    romaji: 'ne',
    type: 'gojuuon',
    ru: 'нэ',
    hiragana: 'ね',
    katakana: 'ネ',
  },
  {
    romaji: 'no',
    type: 'gojuuon',
    ru: 'но',
    hiragana: 'の',
    katakana: 'ノ',
  },
  {
    romaji: 'ha',
    type: 'gojuuon',
    ru: 'ха',
    hiragana: 'は',
    katakana: 'ハ',
  },
  {
    romaji: 'hi',
    type: 'gojuuon',
    ru: 'хи',
    hiragana: 'ひ',
    katakana: 'ヒ',
  },
  {
    romaji: 'hu',
    type: 'gojuuon',
    ru: 'фу',
    hiragana: 'ふ',
    katakana: 'フ',
  },
  {
    romaji: 'he',
    type: 'gojuuon',
    ru: 'хэ',
    hiragana: 'へ',
    katakana: 'ヘ',
  },
  {
    romaji: 'ho',
    type: 'gojuuon',
    ru: 'хо',
    hiragana: 'ほ',
    katakana: 'ホ',
  },
  {
    romaji: 'ma',
    type: 'gojuuon',
    ru: 'ма',
    hiragana: 'ま',
    katakana: 'マ',
  },
  {
    romaji: 'mi',
    type: 'gojuuon',
    ru: 'ми',
    hiragana: 'み',
    katakana: 'ミ',
  },
  {
    romaji: 'mu',
    type: 'gojuuon',
    ru: 'му',
    hiragana: 'む',
    katakana: 'ム',
  },
  {
    romaji: 'me',
    type: 'gojuuon',
    ru: 'мэ',
    hiragana: 'め',
    katakana: 'メ',
  },
  {
    romaji: 'mo',
    type: 'gojuuon',
    ru: 'мо',
    hiragana: 'も',
    katakana: 'モ',
  },
  {
    romaji: 'ya',
    type: 'gojuuon',
    ru: 'я',
    hiragana: 'や',
    katakana: 'ヤ',
  },
  {
    romaji: 'yu',
    type: 'gojuuon',
    ru: 'ю',
    hiragana: 'ゆ',
    katakana: 'ユ',
  },
  {
    romaji: 'yo',
    type: 'gojuuon',
    ru: 'ё',
    hiragana: 'よ',
    katakana: 'ヨ',
  },
  {
    romaji: 'ra',
    type: 'gojuuon',
    ru: 'ра',
    hiragana: 'ら',
    katakana: 'ラ',
  },
  {
    romaji: 'ri',
    type: 'gojuuon',
    ru: 'ри',
    hiragana: 'り',
    katakana: 'リ',
  },
  {
    romaji: 'ru',
    type: 'gojuuon',
    ru: 'ру',
    hiragana: 'る',
    katakana: 'ル',
  },
  {
    romaji: 're',
    type: 'gojuuon',
    ru: 'рэ',
    hiragana: 'れ',
    katakana: 'レ',
  },
  {
    romaji: 'ro',
    type: 'gojuuon',
    ru: 'ро',
    hiragana: 'ろ',
    katakana: 'ロ',
  },
  {
    romaji: 'wa',
    type: 'gojuuon',
    ru: 'ва',
    hiragana: 'わ',
    katakana: 'ワ',
  },
  {
    romaji: 'wo',
    type: 'gojuuon',
    ru: 'во / о',
    hiragana: 'を',
    katakana: 'ヲ',
  },
  {
    romaji: 'n',
    type: 'gojuuon',
    ru: 'н',
    hiragana: 'ん',
    katakana: 'ン',
  },
  {
    romaji: 'ga',
    type: 'dakuon',
    ru: 'га',
    hiragana: 'が',
    katakana: 'ガ',
  },
  {
    romaji: 'gi',
    type: 'dakuon',
    ru: 'ги',
    hiragana: 'ぎ',
    katakana: 'ギ',
  },
  {
    romaji: 'gu',
    type: 'dakuon',
    ru: 'гу',
    hiragana: 'ぐ',
    katakana: 'グ',
  },
  {
    romaji: 'ge',
    type: 'dakuon',
    ru: 'гэ',
    hiragana: 'げ',
    katakana: 'ゲ',
  },
  {
    romaji: 'go',
    type: 'dakuon',
    ru: 'го',
    hiragana: 'ご',
    katakana: 'ゴ',
  },
  {
    romaji: 'za',
    type: 'dakuon',
    ru: 'дза',
    hiragana: 'ざ',
    katakana: 'ザ',
  },
  {
    romaji: 'ji',
    type: 'dakuon',
    ru: 'дзи',
    hiragana: 'じ',
    katakana: 'ジ',
  },
  {
    romaji: 'zu',
    type: 'dakuon',
    ru: 'дзу',
    hiragana: 'ず',
    katakana: 'ズ',
  },
  {
    romaji: 'ze',
    type: 'dakuon',
    ru: 'дзэ',
    hiragana: 'ぜ',
    katakana: 'ゼ',
  },
  {
    romaji: 'zo',
    type: 'dakuon',
    ru: 'дзо',
    hiragana: 'ぞ',
    katakana: 'ゾ',
  },
  {
    romaji: 'da',
    type: 'dakuon',
    ru: 'да',
    hiragana: 'だ',
    katakana: 'ダ',
  },
  {
    romaji: 'ji (dji)',
    type: 'dakuon',
    ru: 'дзи',
    hiragana: 'ぢ',
    katakana: '',
  },
  {
    romaji: 'zu (dzu)',
    type: 'dakuon',
    ru: 'дзу',
    hiragana: 'づ',
    katakana: '',
  },
  {
    romaji: 'de',
    type: 'dakuon',
    ru: 'дэ',
    hiragana: 'で',
    katakana: 'デ',
  },
  {
    romaji: 'do',
    type: 'dakuon',
    ru: 'до',
    hiragana: 'ど',
    katakana: 'ド',
  },
  {
    romaji: 'ba',
    type: 'dakuon',
    ru: 'ба',
    hiragana: 'ば',
    katakana: 'バ',
  },
  {
    romaji: 'bi',
    type: 'dakuon',
    ru: 'би',
    hiragana: 'び',
    katakana: 'ビ',
  },
  {
    romaji: 'bu',
    type: 'dakuon',
    ru: 'бу',
    hiragana: 'ぶ',
    katakana: 'ブ',
  },
  {
    romaji: 'be',
    type: 'dakuon',
    ru: 'бэ',
    hiragana: 'べ',
    katakana: 'ベ',
  },
  {
    romaji: 'bo',
    type: 'dakuon',
    ru: 'бо',
    hiragana: 'ぼ',
    katakana: 'ボ',
  },
  {
    romaji: 'pa',
    type: 'handakuon',
    ru: 'па',
    hiragana: 'ぱ',
    katakana: 'パ',
  },
  {
    romaji: 'pi',
    type: 'handakuon',
    ru: 'пи',
    hiragana: 'ぴ',
    katakana: 'ピ',
  },
  {
    romaji: 'pu',
    type: 'handakuon',
    ru: 'пу',
    hiragana: 'ぷ',
    katakana: 'プ',
  },
  {
    romaji: 'pe',
    type: 'handakuon',
    ru: 'пэ',
    hiragana: 'ぺ',
    katakana: 'ペ',
  },
  {
    romaji: 'po',
    type: 'handakuon',
    ru: 'по',
    hiragana: 'ぽ',
    katakana: 'ポ',
  },
  {
    romaji: '(pause)',
    type: 'sokuon',
    ru: 'удваивает впереди стоящую согласную',
    hiragana: 'っ',
    katakana: 'ッ',
  },
  {
    romaji: 'kya',
    type: 'youon',
    ru: 'кя',
    hiragana: 'きゃ',
    katakana: 'キャ',
  },
  {
    romaji: 'kyu',
    type: 'youon',
    ru: 'кю',
    hiragana: 'きゅ',
    katakana: 'キュ',
  },
  {
    romaji: 'kyo',
    type: 'youon',
    ru: 'кё',
    hiragana: 'きょ',
    katakana: 'キョ',
  },
  {
    romaji: 'sha',
    type: 'youon',
    ru: 'ся',
    hiragana: 'しゃ',
    katakana: 'シャ',
  },
  {
    romaji: 'shu',
    type: 'youon',
    ru: 'сю',
    hiragana: 'しゅ',
    katakana: 'シュ',
  },
  {
    romaji: 'sho',
    type: 'youon',
    ru: 'сё',
    hiragana: 'しょ',
    katakana: 'ショ',
  },
  {
    romaji: 'cha',
    type: 'youon',
    ru: 'тя',
    hiragana: 'ちゃ',
    katakana: 'チャ',
  },
  {
    romaji: 'chu',
    type: 'youon',
    ru: 'тю',
    hiragana: 'ちゅ',
    katakana: 'チュ',
  },
  {
    romaji: 'cho',
    type: 'youon',
    ru: 'тё',
    hiragana: 'ちょ',
    katakana: 'チョ',
  },
  {
    romaji: 'nya',
    type: 'youon',
    ru: 'ня',
    hiragana: 'にゃ',
    katakana: 'ニャ',
  },
  {
    romaji: 'nyu',
    type: 'youon',
    ru: 'ню',
    hiragana: 'にゅ',
    katakana: 'ニュ',
  },
  {
    romaji: 'nyo',
    type: 'youon',
    ru: 'нё',
    hiragana: 'にょ',
    katakana: 'ニョ',
  },
  {
    romaji: 'hya',
    type: 'youon',
    ru: 'хя',
    hiragana: 'ひゃ',
    katakana: 'ヒャ',
  },
  {
    romaji: 'hyu',
    type: 'youon',
    ru: 'хю',
    hiragana: 'ひゅ',
    katakana: 'ヒュ',
  },
  {
    romaji: 'hyo',
    type: 'youon',
    ru: 'хё',
    hiragana: 'ひょ',
    katakana: 'ヒョ',
  },
  {
    romaji: 'mya',
    type: 'youon',
    ru: 'мя',
    hiragana: 'みゃ',
    katakana: 'ミャ',
  },
  {
    romaji: 'myu',
    type: 'youon',
    ru: 'мю',
    hiragana: 'みゅ',
    katakana: 'ミュ',
  },
  {
    romaji: 'myo',
    type: 'youon',
    ru: 'мё',
    hiragana: 'みょ',
    katakana: 'ミョ',
  },
  {
    romaji: 'rya',
    type: 'youon',
    ru: 'ря',
    hiragana: 'りゃ',
    katakana: 'リャ',
  },
  {
    romaji: 'ryu',
    type: 'youon',
    ru: 'рю',
    hiragana: 'りゅ',
    katakana: 'リュ',
  },
  {
    romaji: 'ryo',
    type: 'youon',
    ru: 'рё',
    hiragana: 'りょ',
    katakana: 'リョ',
  },
  {
    romaji: 'gya',
    type: 'youon',
    ru: 'гя',
    hiragana: 'ぎゃ',
    katakana: 'ギャ',
  },
  {
    romaji: 'gyu',
    type: 'youon',
    ru: 'гю',
    hiragana: 'ぎゅ',
    katakana: 'ギュ',
  },
  {
    romaji: 'gyo',
    type: 'youon',
    ru: 'гё',
    hiragana: 'ぎょ',
    katakana: 'ギョ',
  },
  {
    romaji: 'ja',
    type: 'youon',
    ru: 'дзя',
    hiragana: 'じゃ',
    katakana: 'ジャ',
  },
  {
    romaji: 'ju',
    type: 'youon',
    ru: 'дзю',
    hiragana: 'じゅ',
    katakana: 'ジュ',
  },
  {
    romaji: 'jo',
    type: 'youon',
    ru: 'дзё',
    hiragana: 'じょ',
    katakana: 'ジョ',
  },
  {
    romaji: 'ja (dja)',
    type: 'youon',
    ru: 'дзя',
    hiragana: 'ぢゃ',
    katakana: 'ヂャ',
  },
  {
    romaji: 'ju (dju)',
    type: 'youon',
    ru: 'дзю',
    hiragana: 'ぢゅ',
    katakana: 'ヂュ',
  },
  {
    romaji: 'jo (djo)',
    type: 'youon',
    ru: 'дзё',
    hiragana: 'ぢょ',
    katakana: 'ヂョ',
  },
  {
    romaji: 'bya',
    type: 'youon',
    ru: 'бя',
    hiragana: 'びゃ',
    katakana: 'ビャ',
  },
  {
    romaji: 'byu',
    type: 'youon',
    ru: 'бю',
    hiragana: 'びゅ',
    katakana: 'ビュ',
  },
  {
    romaji: 'byo',
    type: 'youon',
    ru: 'бё',
    hiragana: 'びょ',
    katakana: 'ヒョ',
  },
  {
    romaji: 'pya',
    type: 'youon',
    ru: 'пя',
    hiragana: 'ぴゃ',
    katakana: 'ピャ',
  },
  {
    romaji: 'pyu',
    type: 'youon',
    ru: 'пю',
    hiragana: 'ぴゅ',
    katakana: 'ピュ',
  },
  {
    romaji: 'pyo',
    type: 'youon',
    ru: 'пё',
    hiragana: 'ぴょ',
    katakana: 'ピョ',
  },
];

const words = [
  {
    lesson: 1,
    japanese: 'あおい',
    meaning: 'голубой, синий, светло-зеленый;бледный',
    romaji: 'aoi',
  },
  {
    lesson: 1,
    japanese: 'え',
    meaning: 'картина',
    romaji: 'e',
  },
  {
    lesson: 1,
    japanese: 'こうこう',
    meaning: 'средняя школа повышенной ступени',
    romaji: 'kookoo',
  },
  {
    lesson: 1,
    japanese: 'き',
    meaning: 'дерево',
    romaji: 'ki',
  },
  {
    lesson: 1,
    japanese: 'えき',
    meaning: 'станция, вокзал',
    romaji: 'eki',
  },
  {
    lesson: 1,
    japanese: 'おおきい',
    meaning: 'большой',
    romaji: 'ookii',
  },
  {
    lesson: 1,
    japanese: 'きく',
    meaning: 'хризантема',
    romaji: 'kiku',
  },
  {
    lesson: 1,
    japanese: 'えいご',
    meaning: 'английский язык',
    romaji: 'eigo',
  },
  {
    lesson: 1,
    japanese: 'あかい',
    meaning: 'красный',
    romaji: 'akai',
  },
  {
    lesson: 1,
    japanese: 'クーキ',
    meaning: 'пирожное',
    romaji: 'ku-ki',
  },
  {
    lesson: 1,
    japanese: 'たかい',
    meaning: 'высокий; дорогой(о цене)',
    romaji: 'takai',
  },
  {
    lesson: 1,
    japanese: 'ちいさい',
    meaning: 'маленький',
    romaji: 'chiisai',
  },
  {
    lesson: 1,
    japanese: 'うち',
    meaning: 'дом',
    romaji: 'uchi',
  },
  {
    lesson: 1,
    japanese: 'ちず',
    meaning: 'карта',
    romaji: 'chizu',
  },
  {
    lesson: 1,
    japanese: 'だいがく',
    meaning: 'институт; университет',
    romaji: 'daigaku',
  },
  {
    lesson: 1,
    japanese: 'せいと',
    meaning: 'ученик; учащийся',
    romaji: 'seito',
  },
  {
    lesson: 1,
    japanese: 'おしい',
    meaning: 'вкусный',
    romaji: 'oshii',
  },
  {
    lesson: 1,
    japanese: 'タクシー',
    meaning: 'такси',
    romaji: 'takushii',
  },
  {
    lesson: 1,
    japanese: 'スカート',
    meaning: 'юбка',
    romaji: 'suka-to',
  },
  {
    lesson: 1,
    japanese: 'ドア',
    meaning: 'дверь',
    romaji: 'doa',
  },
  {
    lesson: 1,
    japanese: 'スキー',
    meaning: 'лыжи',
    romaji: 'suki-',
  },
  {
    lesson: 1,
    japanese: 'ざっし',
    meaning: 'журнал',
    romaji: 'zasshi',
  },
  {
    lesson: 1,
    japanese: 'ひと',
    meaning: 'человек',
    romaji: 'hito',
  },
  {
    lesson: 1,
    japanese: 'はな',
    meaning: 'цветок',
    romaji: 'hana',
  },
  {
    lesson: 1,
    japanese: 'ひくい',
    meaning: 'низкий',
    romaji: 'hikui',
  },
  {
    lesson: 1,
    japanese: 'がっこう',
    meaning: 'школа',
    romaji: 'gakkou',
  },
  {
    lesson: 1,
    japanese: 'コーヒー',
    meaning: 'кофе',
    romaji: 'ko-hi-',
  },
  {
    lesson: 1,
    japanese: 'ビデオ',
    meaning: 'видео',
    romaji: 'bedeo',
  },
  {
    lesson: 1,
    japanese: 'ビデオカセット',
    meaning: 'видеокассета',
    romaji: 'bedeokasetta',
  },
  {
    lesson: 1,
    japanese: 'ながい',
    meaning: 'длинный, долгий',
    romaji: 'nagai',
  },
  {
    lesson: 1,
    japanese: 'バス',
    meaning: 'автобус',
    romaji: 'basu',
  },
  {
    lesson: 1,
    japanese: 'あなた',
    romaji: 'anata',
    meaning: 'вы(ты)',
  },
  {
    lesson: 1,
    japanese: 'わたし',
    romaji: 'watashi',
    meaning: 'я',
  },
  {
    lesson: 1,
    japanese: 'せんせい',
    romaji: 'sensei',
    meaning: 'учитель, преподаватель',
  },
  {
    lesson: 1,
    japanese: 'あそこ',
    romaji: 'asoko',
    meaning:
      'там (о месте, одинаково удалённом как от говорящего, так и от собеседника)',
  },
  {
    lesson: 1,
    japanese: 'そこ',
    romaji: 'soko',
    meaning: 'здесь, там (о месте, более близком к собеседнику)',
  },
];

const prisma = new PrismaClient();

async function main() {
  const kanaCollection = await prisma.$transaction(
    kana.map((cur) =>
      prisma.kana.upsert({
        where: { romaji: cur.romaji },
        update: {},
        create: cur,
      }),
    ),
  );

  const wordCollection = await prisma.$transaction(
    words.map((cur) =>
      prisma.word.upsert({
        where: { japanese: cur.japanese },
        update: {},
        create: cur,
      }),
    ),
  );

  console.log({
    kanaCollection: kanaCollection.length,
    wordCollection: wordCollection.length,
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
